### ISSUE TITLE
ERROR StatusLogger Could not unregister MBeans for org.apache.logging.log4j2

### ISSUE THREAD

**Issue by ivangfr** [micronaut-projects/micronaut-elasticsearch#56]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

---

Hey guys,

First of all, congrats for the release of the version `2.0.0`!

I've just updated my `movies-api` to the latest Micronaut version (https://github.com/ivangfr/graalvm-quarkus-micronaut-springboot/tree/update-frameworks-version/elasticsearch/micronaut-elasticsearch)
> **Note:** use the branch: **update-frameworks-version**

In short, I can compile the application to native without any problem.
However, when I run it, I am having a problem saying
```
ERROR StatusLogger Could not unregister MBeans for org.apache.logging.log4j2:type=4b6995df
 java.lang.NullPointerException
```
> **Note:** Full log below

Btw, I have the following logging dependencies
```
    runtimeOnly("org.slf4j:log4j-over-slf4j:1.7.30")
    implementation("org.apache.logging.log4j:log4j-api:2.13.3")
    implementation("org.apache.logging.log4j:log4j-core:2.13.3")
```

Researching a little bi about, I think it's related to this [Log4j2 issues #1209](https://github.com/oracle/graal/issues/1209)

Below the simulation.

Thanks!

---

In order to show it, I have 2 terminals:
- `micronaut-elasticsearch-native` terminal
- `curl` terminal

1. Seeing `micronaut-elasticsearch-native` terminal, the app starts fine
   ```
   $ docker run --rm --name micronaut-elasticsearch-native \
       -p 9108:8080 -e ELASTICSEARCH_HOST=elasticsearch --network elasticsearch_default \
       docker.mycompany.com/micronaut-elasticsearch-native:1.0.0

   ./micronaut-elasticsearch: /usr/lib/libstdc++.so.6: no version information available (required by ./micronaut-elasticsearch)
   16:05:46.107 [ForkJoinPool.commonPool-worker-3] WARN  i.m.c.i.binder.jvm.JvmGcMetrics - GC notifications will not be available because MemoryPoolMXBeans are not provided by the JVM
   16:05:46.115 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 77ms. Server Running: http://5d7b1768ffe4:8080
   ```

1. Then, in `curl` terminal, I send a POST request to add a movie. I got 201 as response, OK.
   ```
   curl -i -X POST "localhost:9108/api/movies" -H "Content-type: application/json" -d '{"imdb": "789", "title": "Resident Evil"}'                          ivanfranchin@Ivans-MBP-2
   HTTP/1.1 201 Created
   
   1rr6BXMBpGZGkiftb8l_
   ```

1. Checking `micronaut-elasticsearch-native` terminal, no problem. Just a log confirming that the movie was indexed
   ```
   16:06:05.710 [nioEventLoopGroup-1-2] INFO  c.m.m.service.MovieServiceImpl - Document for 'Movie(imdb=789, title=Resident Evil)' CREATED successfully in ES. The id is: 1rr6BXMBpGZGkiftb8l_
   ```

1. Going back to `curl` terminal, I send a GET request to get the movies. Got 200 as response, OK.
   ```
   $ curl -i localhost:9087/api/books
   HTTP/1.1 200 OK
   
   [{"id":1,"isbn":"123","title":"Learn Java"},{"id":2,"isbn":"123","title":"Learn Docker"}]
   ```

1. However, checking `micronaut-elasticsearch-native` terminal I have the following errors. But, in the end the movies were retrieved.
   ```
   ERROR StatusLogger Could not unregister MBeans for org.apache.logging.log4j2:type=4b6995df
    java.lang.NullPointerException
   	at org.apache.logging.log4j.core.jmx.Server.unregisterAllMatching(Server.java:337)
   	at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:261)
   	at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:165)
   	at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:141)
   	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:629)
   	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:691)
   	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:708)
   	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:263)
   	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:153)
   	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
   	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
   	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:602)
   	at org.elasticsearch.search.builder.SearchSourceBuilder.<clinit>(SearchSourceBuilder.java:84)
   	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
   	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
   	at java.lang.Class.ensureInitialized(DynamicHub.java:499)
   	at org.elasticsearch.action.search.SearchRequest.<init>(SearchRequest.java:121)
   	at com.mycompany.micronautelasticsearch.service.MovieServiceImpl.searchMovies(MovieServiceImpl.java:58)
   	at com.mycompany.micronautelasticsearch.rest.MovieController.searchMovies(MovieController.java:37)
   	at com.mycompany.micronautelasticsearch.rest.$MovieControllerDefinition$$exec2.invokeInternal(Unknown Source)
   	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:146)
   	at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:468)
   	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:313)
   	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:117)
   	at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildResultEmitter$11(RoutingInBoundHandler.java:1304)
   	at io.reactivex.internal.operators.flowable.FlowableDefer.subscribeActual(FlowableDefer.java:35)
   	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
   	at io.reactivex.Flowable.subscribe(Flowable.java:14868)
   	at io.micronaut.configuration.metrics.binder.web.WebMetricsPublisher.subscribe(WebMetricsPublisher.java:153)
   	at io.micronaut.http.server.context.ServerRequestContextFilter$1.subscribe(ServerRequestContextFilter.java:65)
   	at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
   	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
   	at io.reactivex.Flowable.subscribe(Flowable.java:14868)
   	at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildExecutableRoute$5(RoutingInBoundHandler.java:1008)
   	at io.micronaut.web.router.DefaultUriRouteMatch$1.execute(DefaultUriRouteMatch.java:81)
   	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:117)
   	at io.micronaut.http.server.netty.RoutingInBoundHandler.handleRouteMatch(RoutingInBoundHandler.java:686)
   	at io.micronaut.http.server.netty.RoutingInBoundHandler.channelRead0(RoutingInBoundHandler.java:548)
   	at io.micronaut.http.server.netty.RoutingInBoundHandler.channelRead0(RoutingInBoundHandler.java:143)
   	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
   	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:102)
   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
   	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
   	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
   	at io.micronaut.http.netty.stream.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:196)
   	at io.micronaut.http.netty.stream.HttpStreamsServerHandler.channelRead(HttpStreamsServerHandler.java:121)
   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
   	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
   	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
   	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
   	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
   	at io.netty.handler.codec.http.HttpServerKeepAliveHandler.channelRead(HttpServerKeepAliveHandler.java:64)
   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
   	at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:191)
   	at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:153)
   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
   	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
   	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
   	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
   	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
   	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
   	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
   	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
   	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
   	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
   	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
   	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
   	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
   	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
   	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
   	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
   	at java.lang.Thread.run(Thread.java:834)
   	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
   	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
   ...
   16:06:32.708 [nioEventLoopGroup-1-3] INFO  c.m.m.service.MovieServiceImpl - Searching for 'evil' took 262ms and found 1 hits
```

**Comment by moeyui1** [comment]
It seems to be something related to JMX. If you don't need that, `-Dlog4j2.disable.jmx=true` may works.

> JMX support is enabled by default. When Log4j initializes, the StatusLogger, ContextSelector, and all LoggerContexts, LoggerConfigs and Appenders are instrumented with MBeans. To disable JMX completely, and prevent these MBeans from being created, specify system property log4j2.disableJmx to true when you start the Java VM.

**Comment by graemerocher** [comment]
I'm not sure this is related to the elastic search module. It is debatable that may be need a log4j2 module that does this, but @moeyui1's fix seems to be the correct one

**Comment by ivangfr** [comment]
Hey @moeyui1 , I've added `log4j2.disable.jmx: true` into my `application.yml`, compiled to native and had the same problem.

**Comment by moeyui1** [comment]
> Hey @moeyui1 , I've added `log4j2.disable.jmx: true` into my `application.yml`, compiled to native and had the same problem.

Well, according to the following source code of log4j, I think your config didn't take effect for some reason if you got the same problem.

`org/apache/logging/log4j/core/jmx/Server.java`
```java
    public static void reregisterMBeansAfterReconfigure() {
        // avoid creating Platform MBean Server if JMX disabled
        if (isJmxDisabled()) {
            LOGGER.debug("JMX disabled for Log4j2. Not registering MBeans.");
            return;
        }
        final MBeanServer mbs = ManagementFactory.getPlatformMBeanServer();
        reregisterMBeansAfterReconfigure(mbs);
    }
    // ...
    private static boolean isJmxDisabled() {
        return PropertiesUtil.getProperties().getBooleanProperty(PROPERTY_DISABLE_JMX);
    }
    // ...
    private static final String PROPERTY_DISABLE_JMX = "log4j2.disable.jmx";
```

**Comment by graemerocher** [comment]
@ivangfr you would need to pass `-Dlog4j2.disable.jmx=true` to the `native-image` command and possibly also when you run the native image

**Comment by ivangfr** [comment]
Thanks @moeyui1 and @graemerocher for the tips. Yes, now seeing the code that @moeyui1 shared above, by setting correctly the `-Dlog4j2.disable.jmx=true` it should solve the issue.
